---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rte
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rte
rules:
- apiGroups: ["topology.node.k8s.io"]
  resources: ["noderesourcetopologies"]
  verbs: ["create", "update", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rte
subjects:
- kind: ServiceAccount
  name: rte
  namespace: default
roleRef:
  kind: ClusterRole
  name: rte
  apiGroup: rbac.authorization.k8s.io
