---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rte
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rte
rules:
- apiGroups: ["topology.node.k8s.io"]
  resources: ["noderesourcetopologies"]
  verbs: ["create", "update", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rte
subjects:
- kind: ServiceAccount
  name: rte
  namespace: default
roleRef:
  kind: ClusterRole
  name: rte
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: resource-topology-exporter-ds
spec:
  selector:
      matchLabels:
        name: resource-topology
  template:
    metadata:
      labels:
        name: resource-topology
    spec:
      serviceAccountName: rte
      containers:
      - name: resource-topology-exporter-container
        image: ${RTE_CONTAINER_IMAGE}
        command:
        - /bin/resource-topology-exporter
        - --export-namespace=default
        - --watch-namespace=rte
        - --sleep-interval=${RTE_POLL_INTERVAL}
        - --sysfs=/host-sys
        - --kubelet-config-file=/host-var/lib/kubelet/config.yaml
        - --podresources-socket=/host-var/lib/kubelet/pod-resources/kubelet.sock
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: REFERENCE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REFERENCE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REFERENCE_CONTAINER_NAME
          value: shared-pool-container
        volumeMounts:
          - name: host-sys
            mountPath: "/host-sys"
            readOnly: true
          - name: host-conf
            mountPath: "/host-var/lib/kubelet/config.yaml"
            readOnly: true
          - name: host-podresources
            mountPath: "/host-var/lib/kubelet/pod-resources"
      - name: shared-pool-container
        image: gcr.io/google_containers/pause-amd64:3.0
      volumes:
      - name: host-sys
        hostPath:
          path: "/sys"
      - name: host-conf
        hostPath:
          path: "/var/lib/kubelet/config.yaml"
      - name: host-podresources
        hostPath:
          path: "/var/lib/kubelet/pod-resources"
