apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
data:
  config.json: |
    {
        "resourceList": [{
                "resourcePrefix": "openshift.io",
                "resourceName": "sriov",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1015"],
                    "drivers": ["mlx5_core"]
                }
            }
        ]
    }
