name: CI Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: build
      run: make all

    - name: Test
      run: make test-unit
